---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcript-service-prod-deployment
  namespace: dev
  labels:
    app: transcript-service-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcript-service-prod
  template:
    metadata:
      labels:
        app: transcript-service-prod
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: transcript-service-prod-container
          image: us-west1-docker.pkg.dev/cas-dev-env/transcript-service-k8s/transcript-service:$image_tag
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2500m
              memory: 4000Mi
          env:
          - name: project_id
            value: cas-dev-env
          - name: env
            value: prod

---
apiVersion: v1
kind: Service
metadata:
  name: transcript-service-prod-service
  namespace: dev
spec:
  selector:
    app: transcript-service-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcript-service-prod-ingress
  namespace: dev
spec:
  rules:
    - host: "transcript-prod.connectandsell.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transcript-service-prod-service
                port:
                  number: 80
  ingressClassName: nginx-internal

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transcript-service-prod-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transcript-service-prod-deployment
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-internal-controller
  namespace: ingress-nginx-internal
data:
  enable-underscores-in-headers: 'true'
